sudo: required
services:
  - docker
env:
    global:
      - SHA=$(git rev-parse HEAD)
      - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # encrypted file provided by TravisCI CLI
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  # left of pipe : download, right of pipe : install locally on instance assigned by travisCI
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  # add config
  - source $HOME/google-cloud-sdk/path.bash.inc
  # install support for kubectl
  - gcloud components update kubectl
  # authorize google cloud account
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-248503
  - gcloud config set compute/zone us-east1-c
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t willdk3000/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true willdk3000/docker-react npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    # commands will only be run on master branch of github repo
    branch: master